### PR TITLE
Added Bitcoin ABC 0.15.1, 0.16.0, 0.16.1, and 0.16.2

### PR DESCRIPTION
**Pull request by zquestz**
Just adds the last 4 ABC versions.

### CODE REVIEW

**Comment by zquestz** [comment]
Seems you aren't interested in these changes. I am going to close this.

**Comment by madeinquant** [comment]
Dear zquestz,
 Would you comment how to upgrade the latest version 0.16.2 when I was installed amacneil/bitcoin(version": 140200) ? Thank you

**Comment by zquestz** [comment]
All you need to do is deploy the updated image, there are no special steps. =)

**Comment by madeinquant** [comment]
Sorry, new to docker development. No idea how to do that

**Comment by zquestz** [comment]
Just stop the old image, then start the new one. There are no special steps. =)

**Comment by madeinquant** [comment]
1. install and start a docker : docker run -d --rm --name bitcoind-testnet -v /eUSB/sync/bitcoin/testnet/bitcoind:/data -p 18332:18332 -p 18333:18333 amacneil/bitcoin bitcoind -testnet
 
2. docker images : 
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              16.04               f975c5035748        2 weeks ago         112MB
amacneil/bitcoin    latest              d2dcda56bfa4        4 weeks ago         103MB

3. stop a docker : docker stop bitcoin-testnet

I have no idea how to install\start a new image, please comment how to do, thank you.

**Comment by madeinquant** [comment]
I found someone else that updated an original image "nicolasdorier/docker-bitcoin", thank you for comment.

**Comment by amacneil** [comment]
Hi folks - sorry, I haven't had time to maintain this lately, and keeping the docker hub images and versions in sync is very manual due to deficiencies in the docker hub API. I will add a note and update the readme, I am happy for others to fork this project and keep it up to date.

**Pull request closed without merging**
